export interface IngredientEntry {
  id: string;
  canonical: string;
  tamil?: string;
  transliteration?: string;
  aliases: string[];
  category: "vegetable" | "protein" | "legume" | "herb";
}

/** Offline South Indian ingredient catalog (~120 items, 300+ searchable aliases). */
export const INGREDIENT_CATALOG: IngredientEntry[] = [
  { id: "potato", canonical: "Potato", tamil: "உருளைக்கிழங்கு", transliteration: "urulaikilangu", aliases: ["urulai", "urulaikizhangu", "aloo", "alu"], category: "vegetable" },
  { id: "tomato", canonical: "Tomato", tamil: "தக்காளி", transliteration: "thakkali", aliases: ["thakali", "takkali", "tamatar"], category: "vegetable" },
  { id: "onion", canonical: "Onion", tamil: "வெங்காயம்", transliteration: "vengayam", aliases: ["venkayam", "pyaz", "piyaz"], category: "vegetable" },
  { id: "eggplant", canonical: "Eggplant", tamil: "கத்தரிக்காய்", transliteration: "kathirikai", aliases: ["brinjal", "baingan", "kathiri", "kathrikai", "katharikkai"], category: "vegetable" },
  { id: "okra", canonical: "Okra", tamil: "வெண்டைக்காய்", transliteration: "vendaikkai", aliases: ["ladyfinger", "lady finger", "vendakkai", "vendakai", "green jaal", "green jale", "bhindi", "bendakai"], category: "vegetable" },
  { id: "drumstick", canonical: "Drumstick", tamil: "முருங்கைக்காய்", transliteration: "murungakkai", aliases: ["moringa", "murungai", "murungaikai", "drum stick"], category: "vegetable" },
  { id: "bitter-gourd", canonical: "Bitter gourd", tamil: "பாகற்காய்", transliteration: "pavakkai", aliases: ["bittergourd", "karela", "pakarkai", "paavakkai", "bitter melon"], category: "vegetable" },
  { id: "snake-gourd", canonical: "Snake gourd", tamil: "புடலங்காய்", transliteration: "pudalangai", aliases: ["snakegourd", "potlakaaya", "chichinda"], category: "vegetable" },
  { id: "ridge-gourd", canonical: "Ridge gourd", tamil: "பீர்க்கங்காய்", transliteration: "peerkangai", aliases: ["ridgegourd", "turai", "turaiya", "beerakaya"], category: "vegetable" },
  { id: "bottle-gourd", canonical: "Bottle gourd", tamil: "சுரைக்காய்", transliteration: "suraikkai", aliases: ["bottlegourd", "lauki", "doodhi", "sorakkai", "sorakai", "churakka"], category: "vegetable" },
  { id: "ash-gourd", canonical: "Ash gourd", tamil: "நீர்ப்பூசணிக்காய்", transliteration: "neer poosanikai", aliases: ["ashgourd", "winter melon", "poosanikai", "poosani", "kumbalanga"], category: "vegetable" },
  { id: "pumpkin", canonical: "Pumpkin", tamil: "பூசணிக்காய்", transliteration: "poosanikai", aliases: ["parangikkai", "parangikai", "kaddu", "mathanga"], category: "vegetable" },
  { id: "carrot", canonical: "Carrot", tamil: "கேரட்", transliteration: "carrot", aliases: ["carrots", "gajar"], category: "vegetable" },
  { id: "beans", canonical: "Beans", tamil: "அவரைக்காய்", transliteration: "avaraikkai", aliases: ["flat beans", "avarakkai", "sem", "french beans", "green beans"], category: "vegetable" },
  { id: "cluster-beans", canonical: "Cluster beans", tamil: "கோத்தவரை", transliteration: "kothavarangai", aliases: ["clusterbeans", "guvar", "guar", "kothavara"], category: "vegetable" },
  { id: "broad-beans", canonical: "Broad beans", transliteration: "mochai", aliases: ["broadbeans", "mochakottai", "field beans", "avarekalu"], category: "legume" },
  { id: "cowpeas", canonical: "Cowpeas", transliteration: "karamani", aliases: ["cow pea", "lobia", "thattam payir", "black eyed peas"], category: "legume" },
  { id: "cabbage", canonical: "Cabbage", tamil: "முட்டைக்கோஸ்", transliteration: "muttaikos", aliases: ["muttaikose", "patta gobi"], category: "vegetable" },
  { id: "cauliflower", canonical: "Cauliflower", tamil: "பூக்கோஸ்", transliteration: "pookkos", aliases: ["cauli", "gobi", "pookkose"], category: "vegetable" },
  { id: "broccoli", canonical: "Broccoli", aliases: [], category: "vegetable" },
  { id: "capsicum", canonical: "Capsicum", tamil: "குடைமிளகாய்", transliteration: "kudaimilagai", aliases: ["bell pepper", "shimla mirch", "kudamilagai"], category: "vegetable" },
  { id: "green-chilli", canonical: "Green chilli", tamil: "பச்சை மிளகாய்", transliteration: "pachai milagai", aliases: ["green chili", "milagai", "mirchi"], category: "vegetable" },
  { id: "red-chilli", canonical: "Red chilli", tamil: "சிகப்பு மிளகாய்", transliteration: "sigappu milagai", aliases: ["red chili", "dry chilli", "varmilagai"], category: "vegetable" },
  { id: "curry-leaves", canonical: "Curry leaves", tamil: "கருவேப்பிலை", transliteration: "karuveppilai", aliases: ["curryleaves", "karuvepilai", "karivepaku"], category: "herb" },
  { id: "coriander", canonical: "Coriander", tamil: "கொத்தமல்லி", transliteration: "kothamalli", aliases: ["cilantro", "dhania"], category: "herb" },
  { id: "mint", canonical: "Mint", tamil: "புதினா", transliteration: "pudina", aliases: ["pudhina", "pudina leaves"], category: "herb" },
  { id: "spinach", canonical: "Spinach", tamil: "கீரை", transliteration: "keerai", aliases: ["palak", "pasalai keerai"], category: "vegetable" },
  { id: "amaranth", canonical: "Amaranth", tamil: "அரைகீரை", transliteration: "araikeerai", aliases: ["thandu keerai", "mulai keerai", "chaulai"], category: "vegetable" },
  { id: "fenugreek-leaves", canonical: "Fenugreek leaves", tamil: "வெந்தயக்கீரை", transliteration: "vendhaya keerai", aliases: ["methi leaves", "methi"], category: "herb" },
  { id: "radish", canonical: "Radish", tamil: "முள்ளங்கி", transliteration: "mullangi", aliases: ["mooli"], category: "vegetable" },
  { id: "beetroot", canonical: "Beetroot", tamil: "பீட்ரூட்", transliteration: "beetroot", aliases: ["beet", "chukandar"], category: "vegetable" },
  { id: "turnip", canonical: "Turnip", transliteration: "navarattilangu", aliases: ["shalgam"], category: "vegetable" },
  { id: "yam", canonical: "Yam", tamil: "சேனைக்கிழங்கு", transliteration: "senai kilangu", aliases: ["elephant yam", "senai", "suran", "chenai"], category: "vegetable" },
  { id: "taro", canonical: "Taro", transliteration: "seppankilangu", aliases: ["colocasia", "arbi", "cheppankilangu", "seppankizhangu"], category: "vegetable" },
  { id: "sweet-potato", canonical: "Sweet potato", transliteration: "sakkaravalli kilangu", aliases: ["sweetpotato", "sakkaravalli", "shakarkandi"], category: "vegetable" },
  { id: "raw-banana", canonical: "Raw banana", tamil: "வாழைக்காய்", transliteration: "vaalaikkai", aliases: ["plantain", "vazhakkai", "vaazhakkai", "green banana", "kachha kela"], category: "vegetable" },
  { id: "banana-stem", canonical: "Banana stem", tamil: "வாழைத்தண்டு", transliteration: "vaazhai thandu", aliases: ["bananastem", "vazhaithandu", "vaazhaithandu"], category: "vegetable" },
  { id: "banana-flower", canonical: "Banana flower", tamil: "வாழைப்பூ", transliteration: "vaazhaipoo", aliases: ["bananaflower", "vazhaipoo", "vaazhaipoo"], category: "vegetable" },
  { id: "coconut", canonical: "Coconut", tamil: "தேங்காய்", transliteration: "thengai", aliases: ["thengai", "nariyal", "copra"], category: "vegetable" },
  { id: "cucumber", canonical: "Cucumber", tamil: "வெள்ளரிக்காய்", transliteration: "vellarikkai", aliases: ["kakdi", "dosakaya"], category: "vegetable" },
  { id: "ivy-gourd", canonical: "Ivy gourd", transliteration: "kovakkai", aliases: ["tindora", "tondli"], category: "vegetable" },
  { id: "raw-mango", canonical: "Raw mango", tamil: "மாங்காய்", transliteration: "maangaai", aliases: ["green mango", "manga", "kacha aam"], category: "vegetable" },
  { id: "lemon", canonical: "Lemon", tamil: "எலுமிச்சை", transliteration: "elumichai", aliases: ["lime", "nimbu"], category: "vegetable" },
  { id: "garlic", canonical: "Garlic", tamil: "பூண்டு", transliteration: "poondu", aliases: ["lasun"], category: "herb" },
  { id: "ginger", canonical: "Ginger", tamil: "இஞ்சி", transliteration: "inji", aliases: ["adrak"], category: "herb" },
  { id: "green-peas", canonical: "Green peas", tamil: "பட்டாணி", transliteration: "pattani", aliases: ["peas", "matar"], category: "legume" },
  { id: "corn", canonical: "Corn", tamil: "சோளம்", transliteration: "cholam", aliases: ["sweet corn", "makka", "bhutta"], category: "vegetable" },
  { id: "mushroom", canonical: "Mushroom", tamil: "காளான்", transliteration: "kaalan", aliases: ["button mushroom"], category: "vegetable" },
  { id: "baby-corn", canonical: "Baby corn", aliases: ["babycorn"], category: "vegetable" },
  { id: "spring-onion", canonical: "Spring onion", tamil: "வெங்காயத்தாள்", transliteration: "vengayam thaal", aliases: ["scallion", "green onion"], category: "herb" },
  { id: "shallots", canonical: "Shallots", transliteration: "chinna vengayam", aliases: ["sambar onion", "small onion", "red onion"], category: "vegetable" },
  { id: "chow-chow", canonical: "Chow chow", transliteration: "chow chow", aliases: ["chayote", "bangalore kathrikai"], category: "vegetable" },
  { id: "knol-khol", canonical: "Knol khol", transliteration: "nool kol", aliases: ["kohlrabi", "noolkol"], category: "vegetable" },
  { id: "jackfruit", canonical: "Jackfruit", transliteration: "palaa", aliases: ["chakka", "kathal"], category: "vegetable" },
  { id: "raw-jackfruit", canonical: "Raw jackfruit", transliteration: "palaakkai", aliases: ["young jackfruit"], category: "vegetable" },
  { id: "tapioca", canonical: "Tapioca", transliteration: "maravalli kilangu", aliases: ["kappa", "kuchi kilangu", "cassava"], category: "vegetable" },
  { id: "gongura", canonical: "Gongura", tamil: "pulicha keerai", transliteration: "pulicha keerai", aliases: ["sorrel leaves", "ambadi"], category: "vegetable" },
  { id: "manathakkali", canonical: "Manathakkali", transliteration: "manathakkali", aliases: ["black nightshade", "sun berry"], category: "vegetable" },
  { id: "murungai-keerai", canonical: "Murungai keerai", tamil: "முருங்கைக் கீரை", transliteration: "murungai keerai", aliases: ["drumstick leaves", "moringa leaves"], category: "vegetable" },
  { id: "ponnanganni", canonical: "Ponnanganni", transliteration: "ponnanganni", aliases: ["ponnanganni keerai", "water amaranth"], category: "vegetable" },
  { id: "sirukeerai", canonical: "Sirukeerai", tamil: "சிறுகீரை", transliteration: "sirukeerai", aliases: ["siru keerai"], category: "vegetable" },
  { id: "keerai", canonical: "Keerai", tamil: "கீரை", transliteration: "keerai", aliases: ["mixed greens", "leafy greens", "greens"], category: "vegetable" },
  { id: "pointed-gourd", canonical: "Pointed gourd", transliteration: "parwal", aliases: ["parwal", "potol"], category: "vegetable" },
  { id: "mixed-vegetables", canonical: "Mixed vegetables", aliases: ["veg mix", "sabzi mix"], category: "vegetable" },
  { id: "fish", canonical: "Fish", tamil: "மீன்", transliteration: "meen", aliases: ["meen", "machli", "seafood"], category: "protein" },
  { id: "chicken", canonical: "Chicken", tamil: "கோழி", transliteration: "kozhi", aliases: ["kozhi", "murgh"], category: "protein" },
  { id: "egg", canonical: "Egg", tamil: "முட்டை", transliteration: "muttai", aliases: ["muttai", "anda", "eggs"], category: "protein" },
  { id: "prawn", canonical: "Prawn", tamil: "இறால்", transliteration: "iral", aliases: ["shrimp", "eral", "jhinga", "chemmeen"], category: "protein" },
  { id: "crab", canonical: "Crab", tamil: "nandu", transliteration: "nandu", aliases: ["crabs"], category: "protein" },
  { id: "mutton", canonical: "Mutton", tamil: "ஆடு", transliteration: "aadu", aliases: ["goat", "lamb"], category: "protein" },
  { id: "paneer", canonical: "Paneer", aliases: ["cottage cheese"], category: "protein" },
  { id: "tofu", canonical: "Tofu", aliases: ["soya paneer"], category: "protein" },
  { id: "soya-chunks", canonical: "Soya chunks", aliases: ["soy chunks", "meal maker"], category: "protein" },
  { id: "toor-dal", canonical: "Toor dal", transliteration: "thuvaram paruppu", aliases: ["arhar dal", "thuvaram paruppu"], category: "legume" },
  { id: "moong-dal", canonical: "Moong dal", transliteration: "pasipayaru", aliases: ["moong", "green gram dal"], category: "legume" },
  { id: "urad-dal", canonical: "Urad dal", transliteration: "ulundhu", aliases: ["black gram dal", "ulundu"], category: "legume" },
  { id: "chana-dal", canonical: "Chana dal", transliteration: "kadalai paruppu", aliases: ["bengal gram dal"], category: "legume" },
  { id: "chickpeas", canonical: "Chickpeas", transliteration: "kondakadalai", aliases: ["chana", "chole", "garbanzo"], category: "legume" },
  { id: "black-chickpeas", canonical: "Black chickpeas", transliteration: "karuppu kondakadalai", aliases: ["kala chana"], category: "legume" },
  { id: "kidney-beans", canonical: "Kidney beans", aliases: ["rajma"], category: "legume" },
  { id: "horse-gram", canonical: "Horse gram", transliteration: "kollu", aliases: ["kollu paruppu"], category: "legume" },
  { id: "double-beans", canonical: "Double beans", transliteration: "muttaikottai", aliases: ["butter beans", "lima beans"], category: "legume" },
  { id: "field-beans", canonical: "Field beans", transliteration: "avarekai", aliases: ["avarekalu", "hyacinth beans"], category: "legume" },
  { id: "green-gram", canonical: "Green gram", transliteration: "pachai payaru", aliases: ["moong whole", "whole green gram"], category: "legume" },
  { id: "black-gram", canonical: "Black gram", transliteration: "karuppu ulundhu", aliases: ["whole urad"], category: "legume" },
  { id: "zucchini", canonical: "Zucchini", aliases: ["courgette"], category: "vegetable" },
  { id: "celery", canonical: "Celery", aliases: [], category: "vegetable" },
  { id: "lettuce", canonical: "Lettuce", aliases: [], category: "vegetable" },
  { id: "papaya", canonical: "Papaya", transliteration: "papali", aliases: ["papita"], category: "vegetable" },
  { id: "banana", canonical: "Banana", transliteration: "vazhai", aliases: ["ripe banana", "pazham"], category: "vegetable" },
  { id: "apple", canonical: "Apple", aliases: ["seb"], category: "vegetable" },
  { id: "grapes", canonical: "Grapes", transliteration: "thiratchai", aliases: ["angur"], category: "vegetable" },
  { id: "pomegranate", canonical: "Pomegranate", transliteration: "madhulai", aliases: ["anar"], category: "vegetable" },
  { id: "guava", canonical: "Guava", transliteration: "koyya", aliases: ["amrood"], category: "vegetable" },
  { id: "watermelon", canonical: "Watermelon", transliteration: "tharbooz", aliases: ["tarbooj"], category: "vegetable" },
  { id: "muskmelon", canonical: "Muskmelon", transliteration: "kirni pazham", aliases: ["cantaloupe", "kharbooja"], category: "vegetable" },
  { id: "sapota", canonical: "Sapota", aliases: ["chikoo"], category: "vegetable" },
  { id: "pineapple", canonical: "Pineapple", transliteration: "annasi", aliases: ["annanasa"], category: "vegetable" },
  { id: "baby-potato", canonical: "Baby potato", transliteration: "chinna urulaikilangu", aliases: ["small potato"], category: "vegetable" },
  { id: "tomato-local", canonical: "Local tomato", transliteration: "naatu thakkali", aliases: ["country tomato"], category: "vegetable" },
  { id: "green-tomato", canonical: "Green tomato", transliteration: "pachai thakkali", aliases: [], category: "vegetable" },
  { id: "brinjal-small", canonical: "Small brinjal", transliteration: "gundu kathirikai", aliases: ["small brinjal"], category: "vegetable" },
  { id: "brinjal-long", canonical: "Long brinjal", transliteration: "neel kathirikai", aliases: ["long eggplant"], category: "vegetable" },
  { id: "yellow-pumpkin", canonical: "Yellow pumpkin", transliteration: "parangikkai", aliases: ["parangikai"], category: "vegetable" },
  { id: "white-pumpkin", canonical: "White pumpkin", transliteration: "poosanikai", aliases: ["white pumpkin"], category: "vegetable" },
  { id: "elephant-yam", canonical: "Elephant yam", transliteration: "senai kilangu", aliases: ["senai", "suran"], category: "vegetable" },
  { id: "purple-yam", canonical: "Purple yam", transliteration: "rasa valli kilangu", aliases: ["ratalu", "kand"], category: "vegetable" },
  { id: "lotus-stem", canonical: "Lotus stem", transliteration: "thamarai thandu", aliases: ["lotus root", "kamal kakdi"], category: "vegetable" },
  { id: "bamboo-shoots", canonical: "Bamboo shoots", transliteration: "moongil kilangu", aliases: ["bamboo shoot"], category: "vegetable" },
  { id: "raw-papaya", canonical: "Raw papaya", transliteration: "pachai papali", aliases: ["green papaya"], category: "vegetable" },
  { id: "breadfruit", canonical: "Breadfruit", transliteration: "navapalam", aliases: ["seema chakka"], category: "vegetable" },
  { id: "colocasia-leaves", canonical: "Colocasia leaves", transliteration: "kezhangu ilai", aliases: ["arbi leaves"], category: "vegetable" },
  { id: "agathi-keerai", canonical: "Agathi keerai", transliteration: "agathi keerai", aliases: ["agathi", "agasthe"], category: "vegetable" },
  { id: "mustard-greens", canonical: "Mustard greens", transliteration: "kadugu keerai", aliases: ["sarson ka saag"], category: "vegetable" },
  { id: "radish-leaves", canonical: "Radish leaves", transliteration: "mullangi keerai", aliases: [], category: "vegetable" },
  { id: "beet-greens", canonical: "Beet greens", transliteration: "beetroot keerai", aliases: [], category: "vegetable" },
  { id: "basil", canonical: "Basil", transliteration: "thulasi", aliases: ["tulsi"], category: "herb" },
  { id: "dill", canonical: "Dill", transliteration: "sathakuppai", aliases: ["soa"], category: "herb" },
  { id: "rocket-leaves", canonical: "Rocket leaves", aliases: ["arugula"], category: "herb" },
  { id: "red-bell-pepper", canonical: "Red bell pepper", aliases: ["red capsicum"], category: "vegetable" },
  { id: "yellow-bell-pepper", canonical: "Yellow bell pepper", aliases: [], category: "vegetable" },
  { id: "baby-spinach", canonical: "Baby spinach", aliases: [], category: "vegetable" },
  { id: "sponge-gourd", canonical: "Sponge gourd", transliteration: "nethi beerakaya", aliases: ["luffa"], category: "vegetable" },
  { id: "apple-gourd", canonical: "Apple gourd", transliteration: "tinda", aliases: ["tendli"], category: "vegetable" },
  { id: "water-chestnut", canonical: "Water chestnut", aliases: ["singhara"], category: "vegetable" },
  { id: "lotus-seeds", canonical: "Lotus seeds", transliteration: "thamarai vithai", aliases: ["makhana", "fox nuts"], category: "legume" },
  { id: "soya-beans", canonical: "Soya beans", aliases: ["edamame"], category: "legume" },
  { id: "beef", canonical: "Beef", aliases: [], category: "protein" },
  { id: "tender-coconut", canonical: "Tender coconut", transliteration: "ilaneer", aliases: ["young coconut"], category: "vegetable" },
  { id: "ridge-gourd-vathal", canonical: "Ridge gourd vathal", transliteration: "peerkangai vathal", aliases: ["dried ridge gourd"], category: "vegetable" },
  { id: "drumstick-pod", canonical: "Drumstick pod", transliteration: "murungakkai", aliases: ["drumstick vegetable"], category: "vegetable" },
  { id: "colocasia-stem", canonical: "Colocasia stem", transliteration: "seppankilangu thandu", aliases: ["arbi stem"], category: "vegetable" },
  { id: "taro-leaves", canonical: "Taro leaves", transliteration: "seppankilangu ilai", aliases: ["arbi patta"], category: "vegetable" },
  { id: "sorrel", canonical: "Sorrel", transliteration: "pulicha keerai", aliases: ["gongura leaves"], category: "vegetable" },
  { id: "cherry-tomato", canonical: "Cherry tomato", aliases: ["grape tomato"], category: "vegetable" },
  { id: "brussels-sprouts", canonical: "Brussels sprouts", aliases: [], category: "vegetable" },
  { id: "asparagus", canonical: "Asparagus", aliases: [], category: "vegetable" },
  { id: "artichoke", canonical: "Artichoke", aliases: [], category: "vegetable" },
];

export function normalizeAlias(text: string): string {
  return text.trim().toLowerCase().replace(/\s+/g, " ");
}

export interface IngredientSearchResult {
  id: string;
  canonical: string;
  tamil?: string;
  transliteration?: string;
  matchedAlias: string;
  matchType: "exact" | "prefix" | "contains" | "fuzzy";
  score: number;
}
