import { useCallback, useState, useEffect } from "react";
import { Compass, ChefHat, CalendarDays, User } from "lucide-react";
import { motion } from "motion/react";
import { ActiveScreen, Meal } from "./types";
import {
  MealLogEntry,
  MealLogItemInput,
  MealLogType,
  todayIso,
} from "../shared/mealLogs";
import { useUser } from "./useUser";
import HomeView from "./components/HomeView";
import KitchenView from "./components/KitchenView";
import LogsView from "./components/LogsView";
import ProfileView from "./components/ProfileView";
import RecipeDetailModal from "./components/RecipeDetailModal";

export default function App() {
  const { userId } = useUser();
  const [activeTab, setActiveTab] = useState<ActiveScreen>("home");
  const [meals, setMeals] = useState<Meal[]>([]);
  const [logDate, setLogDate] = useState<string>(todayIso());
  // Meals are stored with the date they were loaded for. Responses can land out
  // of order when the day is switched quickly, and a food diary must never show
  // one day's meals under another day's heading.
  const [loadedDay, setLoadedDay] = useState<{ date: string; meals: MealLogEntry[] }>({
    date: todayIso(),
    meals: [],
  });
  const dayMeals = loadedDay.date === logDate ? loadedDay.meals : [];
  const [selectedMeal, setSelectedMeal] = useState<Meal | null>(null);
  const [isDetailOpen, setIsDetailOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    fetch("/api/meals")
      .then((res) => res.json())
      .then((data) => setMeals(data.meals || []))
      .catch((err) => console.error("Failed to load Vigadi meals:", err))
      .finally(() => setIsLoading(false));
  }, []);

  // The diary only ever holds the day being looked at, so switching days is a
  // fresh read rather than a filter over everything ever logged.
  const fetchDay = useCallback(async () => {
    try {
      const res = await fetch(`/api/logs/${userId}?date=${logDate}`);
      if (!res.ok) return;
      const data = await res.json();
      // The response says which day it is for, so a late arrival cannot be
      // mistaken for the day now on screen.
      setLoadedDay({ date: data.date ?? logDate, meals: data.meals || [] });
    } catch (err) {
      console.error("Failed to load the diary:", err);
    }
  }, [userId, logDate]);

  useEffect(() => {
    fetchDay();
  }, [fetchDay]);

  // 1. Log dishes into a meal on the selected day
  const handleSaveMeal = async (
    mealType: MealLogType,
    dishes: MealLogItemInput[]
  ): Promise<{ ok: boolean; error?: string }> => {
    try {
      const res = await fetch(`/api/logs/${userId}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ date: logDate, mealType, dishes }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) return { ok: false, error: data.error || "Could not save that meal." };
      setLoadedDay({ date: data.date ?? logDate, meals: data.meals || [] });
      return { ok: true };
    } catch {
      return { ok: false, error: "Network error — check your connection." };
    }
  };

  // 2. Log a suggested combo from the recipe drawer as one meal
  const handleLogMeal = async (meal: Meal) => {
    const mealType = (meal.category || "").toLowerCase();
    await handleSaveMeal(
      (["breakfast", "lunch", "dinner", "snack"].includes(mealType)
        ? mealType
        : "lunch") as MealLogType,
      // A combo is its dishes, so it lands as separate rows rather than one
      // long name — the same shape as typing them in by hand.
      (meal.subComponents?.length ? meal.subComponents : [meal.recipeName]).map((name) => ({
        name,
      }))
    );
  };

  // 3. Delete a whole meal
  const handleDeleteMeal = async (mealId: string) => {
    try {
      const res = await fetch(`/api/logs/${userId}/${mealId}`, { method: "DELETE" });
      if (res.ok) await fetchDay();
    } catch (err) {
      console.error("Failed deleting meal:", err);
    }
  };

  // 4. Delete one dish from a meal
  const handleDeleteItem = async (mealId: string, itemId: number) => {
    try {
      const res = await fetch(`/api/logs/${userId}/${mealId}/items/${itemId}`, {
        method: "DELETE",
      });
      if (res.ok) await fetchDay();
    } catch (err) {
      console.error("Failed deleting dish:", err);
    }
  };

  // 5. Clear the whole diary
  const handleResetLogs = async () => {
    if (!window.confirm("Clear every meal you have logged? This cannot be undone.")) return;
    try {
      const res = await fetch(`/api/logs/${userId}/reset`, { method: "POST" });
      if (res.ok) await fetchDay();
    } catch (err) {
      console.error("Error clearing the diary:", err);
    }
  };

  // Select meal to open the sliding details drawer
  const handleSelectMeal = (meal: Meal) => {
    setSelectedMeal(meal);
    setIsDetailOpen(true);
  };

  // Handle created meals generated by Gemini AI
  const handleSelectCreatedMeals = (newMeals: Meal[]) => {
    setMeals((prev) => {
      const filtered = newMeals.filter(m => !prev.some(p => p.recipeName === m.recipeName));
      return [...filtered, ...prev];
    });
  };

  if (isLoading) {
    return (
      <div className="fixed inset-0 flex flex-col items-center justify-center bg-cream text-espresso space-y-4">
        <div className="relative w-12 h-12 flex items-center justify-center">
          <div className="w-12 h-12 border-4 border-matcha border-t-bakedclay rounded-full animate-spin" />
          <span className="absolute text-xs leading-none">🌱</span>
        </div>
        <p className="text-xs font-mono uppercase tracking-widest text-espresso/60 font-bold animate-pulse">
          Balancing biophilic cellular energy...
        </p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-cream text-espresso flex justify-center selection:bg-matcha selection:text-espresso" id="app-canvas">
      {/* Container simulating high-end mobile interface or standard narrow desktop view */}
      <div className="w-full max-w-md min-h-screen flex flex-col bg-cream shadow-premium border-x border-matcha/40 relative pb-20">
        
        {/* Top Header branding */}
        <header className="px-6 py-4 flex items-center justify-between border-b border-matcha/20 bg-cream/80 backdrop-blur-md sticky top-0 z-40">
          <div className="flex items-center gap-1.5 cursor-pointer" onClick={() => setActiveTab("home")} id="brand-logo">
            <span className="text-xl">🥗</span>
            <span className="font-display font-bold text-lg tracking-tight text-espresso">
              v í g a d i
            </span>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-mono tracking-wider text-sage font-bold bg-matcha px-2.5 py-1 rounded-sm uppercase">
              Morning Matcha Theme
            </span>
            {/* Click avatar to go directly to profile */}
            <div 
              onClick={() => setActiveTab("profile")}
              className="w-8 h-8 rounded-full overflow-hidden border border-matcha cursor-pointer hover:border-bakedclay/60 transition-colors shadow-xs shrink-0"
              id="top-avatar-toggle"
            >
              <img
                src="https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80"
                alt="Emma"
                className="w-full h-full object-cover"
                referrerPolicy="no-referrer"
              />
            </div>
          </div>
        </header>

        {/* Scrollable Core View Container */}
        <main className="flex-1 px-6 pt-5 overflow-y-auto">
          {activeTab === "home" && (
            <HomeView 
              meals={meals} 
              onSelectMeal={handleSelectMeal} 
              onNavigateToTab={(tab) => setActiveTab(tab)}
            />
          )}

          {activeTab === "kitchen" && (
            <KitchenView 
              onSelectMeal={handleSelectMeal} 
              onSelectCreatedMeals={handleSelectCreatedMeals}
            />
          )}

          {activeTab === "logs" && (
            <LogsView
              date={logDate}
              meals={dayMeals}
              userId={userId}
              onDateChange={setLogDate}
              onSaveMeal={handleSaveMeal}
              onDeleteMeal={handleDeleteMeal}
              onDeleteItem={handleDeleteItem}
              onResetLogs={handleResetLogs}
            />
          )}

          {activeTab === "profile" && (
            <ProfileView 
              onSelectMealById={(id) => {
                const found = meals.find(m => m.id === id);
                if (found) handleSelectMeal(found);
              }}
            />
          )}
        </main>

        {/* Persistent Bottom Tab Navigation Ribbon */}
        <nav className="fixed bottom-0 left-1/2 -translate-x-1/2 w-full max-w-md bg-cream/95 backdrop-blur-md border-t border-matcha/80 px-6 py-2 flex items-center justify-between shadow-premium z-40">
          {/* Tab buttons */}
          <button
            onClick={() => setActiveTab("home")}
            className={`flex flex-col items-center gap-1 p-1.5 relative transition-all ${
              activeTab === "home" ? "text-bakedclay" : "text-espresso/50 hover:text-espresso"
            }`}
            id="tab-btn-home"
          >
            {activeTab === "home" && (
              <motion.div layoutId="active-dot" className="absolute -top-2 w-1.5 h-1.5 rounded-full bg-bakedclay" />
            )}
            <Compass className="w-5 h-5" />
            <span className="text-[9px] font-mono font-bold uppercase tracking-wider">Explore</span>
          </button>

          <button
            onClick={() => setActiveTab("kitchen")}
            className={`flex flex-col items-center gap-1 p-1.5 relative transition-all ${
              activeTab === "kitchen" ? "text-bakedclay" : "text-espresso/50 hover:text-espresso"
            }`}
            id="tab-btn-kitchen"
          >
            {activeTab === "kitchen" && (
              <motion.div layoutId="active-dot" className="absolute -top-2 w-1.5 h-1.5 rounded-full bg-bakedclay" />
            )}
            <ChefHat className="w-5 h-5" />
            <span className="text-[9px] font-mono font-bold uppercase tracking-wider">Kitchen</span>
          </button>

          <button
            onClick={() => setActiveTab("logs")}
            className={`flex flex-col items-center gap-1 p-1.5 relative transition-all ${
              activeTab === "logs" ? "text-bakedclay" : "text-espresso/50 hover:text-espresso"
            }`}
            id="tab-btn-logs"
          >
            {activeTab === "logs" && (
              <motion.div layoutId="active-dot" className="absolute -top-2 w-1.5 h-1.5 rounded-full bg-bakedclay" />
            )}
            <CalendarDays className="w-5 h-5" />
            <span className="text-[9px] font-mono font-bold uppercase tracking-wider">Logs</span>
          </button>

          <button
            onClick={() => setActiveTab("profile")}
            className={`flex flex-col items-center gap-1 p-1.5 relative transition-all ${
              activeTab === "profile" ? "text-bakedclay" : "text-espresso/50 hover:text-espresso"
            }`}
            id="tab-btn-profile"
          >
            {activeTab === "profile" && (
              <motion.div layoutId="active-dot" className="absolute -top-2 w-1.5 h-1.5 rounded-full bg-bakedclay" />
            )}
            <User className="w-5 h-5" />
            <span className="text-[9px] font-mono font-bold uppercase tracking-wider">Profile</span>
          </button>
        </nav>

        {/* Recipe Drawer Sheets Modal component overlay */}
        <RecipeDetailModal 
          meal={selectedMeal} 
          isOpen={isDetailOpen} 
          onClose={() => setIsDetailOpen(false)} 
          onLogMeal={handleLogMeal}
        />

      </div>
    </div>
  );
}
